In [3]:
import numpy as np

In [4]:
Banking_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [4]:
print(f"\ndata shape:{Banking_data.shape}")


data shape:(10, 5)


In [5]:
identity_matrix =np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
zeros_array = np.zeros(8)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [8]:
range_array=np.arange(0,15)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
linspace_array=np.linspace(0,100,8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [10]:
print(f"shape:{Banking_data.shape}")

shape:(10, 5)


In [11]:
print(f"data type:{Banking_data.dtype}")

data type:float64


In [12]:
print(f"size:{Banking_data.size}")

size:50


In [13]:
print(f"Dimension:{Banking_data.ndim}")

Dimension:2


In [14]:
print(f"Memory size:{Banking_data.nbytes}bytes")

Memory size:400bytes


In [15]:
first_row=Banking_data[0]
print(first_row)

[1001.     29.99   45.      4.2    15.  ]


In [16]:
last_row=Banking_data[-1]
print(last_row)

[1010.     59.99   34.      4.4    10.  ]


In [17]:
price_column=Banking_data[:,1]
print(price_column)

[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [18]:
subset=Banking_data[:4,:3]
print(subset)

[[1001.     29.99   45.  ]
 [1002.     49.99   32.  ]
 [1003.     19.99   78.  ]
 [1004.     89.99   12.  ]]


In [19]:
rows_3_to_7=Banking_data[3:7]
print(rows_3_to_7)

[[1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]]


In [20]:
total_price=np.sum(Banking_data[:,1])
print(f"total price:${total_price:.2f}")

total price:$481.90


In [21]:
mean_price = np.mean(Banking_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")

Mean price: $48.19


In [22]:
std_price = np.std(Banking_data[:, 1])
print(f"Standard deviation of prices: ${std_price:.2f}")


Standard deviation of prices: $24.70


In [23]:
var_price = np.var(Banking_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")

Variance of prices: $609.96


In [24]:
median_price = np.median(Banking_data[:, 1])
print(f"Median price: ${median_price:.2f}")

Median price: $44.99


In [29]:
min_account_balance=np.min(Banking_data[:,1])
max_account_balance=np.max(Banking_data[:,1])
print(f"Minimum account_balance:${min_account_balance:.2f}")
print(f"Maximum account_balance:${max_account_balance:.2f}")

Minimum account_balance:$15.99
Maximum account_balance:$89.99


In [31]:
min_qty=np.min(Banking_data[:,2])
max_qty=np.max(Banking_data[:,2])
print(f"minimum quantity:{min_qty}")
print(f"maximum quantity:{max_qty}")

minimum quantity:12.0
maximum quantity:95.0


In [32]:
percentiles=np.percentile(Banking_data[:,1],[25,50,75])
print(f"25th percentile:${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")

25th percentile:$26.99
50th percentile: $44.99
75th percentile: $67.49


In [33]:
correlation = np.corrcoef(Banking_data[:, 1], Banking_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")

Correlation: -0.9291


In [34]:
covariance = np.cov(Banking_data[:, 1], Banking_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")

Covariance: -653.4444


In [5]:
reshaped_5x10=Banking_data.reshape(5,10)
print(reshaped_5x10)

[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [6]:
flattened=Banking_data.flatten()
print(flattened)

[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [7]:
transposed=Banking_data.T
print(transposed)

[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [8]:
split_vertical=np.vsplit(Banking_data,2)
print("first part:")
print(split_vertical[0])
print("\n second part:")
print(split_vertical[1])

first part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

 second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [ ]:
split_horizontal = np.array_split(Banking_data, 2, axis=1)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])

First part:
[[1001.     29.99   45.  ]
 [1002.     49.99   32.  ]
 [1003.     19.99   78.  ]
 [1004.     89.99   12.  ]
 [1005.     15.99   95.  ]
 [1006.     69.99   28.  ]
 [1007.     39.99   56.  ]
 [1008.     79.99   18.  ]
 [1009.     25.99   67.  ]
 [1010.     59.99   34.  ]]

Second part:
[[ 4.2 15. ]
 [ 4.5  8. ]
 [ 3.8 22. ]
 [ 4.7  5. ]
 [ 4.  18. ]
 [ 4.3 12. ]
 [ 3.9 20. ]
 [ 4.6  7. ]
 [ 4.1 16. ]
 [ 4.4 10. ]]


In [18]:
account_balance=Banking_data[Banking_data[:,1]>100]
print(account_balance)

[]


In [23]:
credit_score=Banking_data[Banking_data[:,3]>800]
print(credit_score)

[]


In [24]:
credit_score = Banking_data[(Banking_data[:,3]>50) & (Banking_data[:,1]<750)]
print(credit_score)

[]


In [25]:
account_balance=np.sum((Banking_data[:,1]>=10000)) & (Banking_data[:,1]<=100000)
print(account_balance)

[0 0 0 0 0 0 0 0 0 0]


In [26]:
higest_credit_score=np.argmax(Banking_data[:,3])
print(higest_credit_score)

3


In [5]:
account_balance=Banking_data[Banking_data[:,1].argsort()]
print(account_balance)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [6]:
credit_score_desc = Banking_data[(-Banking_data[:,2]).argsort()]
print(credit_score_desc)

[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]


In [7]:
active_years_sorted_indices=np.argsort(Banking_data[:,4])
print(active_years_sorted_indices)

[3 7 1 9 5 0 8 4 6 2]


In [ ]:
second_higest_account_balance=Banking_data[]


In [9]:
second_highest_salary_idx = np.argsort(Banking_data[:, 1])[-2]
second_highest_customer = Banking_data[second_highest_salary_idx]
print(f"Customer ID: {second_highest_customer[0]}, Account Balance: ${second_highest_customer[1]:.2f}")

Customer ID: 1008.0, Account Balance: $79.99


In [11]:
lowest_transaction_idx = np.argmin(Banking_data[:, 2])
lowest_customer = Banking_data[lowest_transaction_idx]
print(f"Customer ID: {lowest_customer[0]}, Transaction Count: {lowest_customer[2]}")

Customer ID: 1004.0, Transaction Count: 12.0


In [12]:
absolute_values = np.abs(Banking_data)
print(absolute_values)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [13]:
sqrt_account_balance = np.sqrt(Banking_data[:, 1])
print(sqrt_account_balance)

[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]


In [14]:
squared_credit_score = np.square(Banking_data[:, 2])
print(squared_credit_score)

[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]


In [15]:
exp_all_transations = np.exp(Banking_data[:, 3])
print(exp_all_transations)

[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876   81.45086866]


In [16]:
log_account_balance = np.log(Banking_data[:, 1])
print(log_account_balance)


[3.40086399 3.91182299 2.99523215 4.49969855 2.77196353 4.24835237
 3.68862942 4.38190163 3.25771185 4.09417788]


In [17]:
cumsum_account_balance = np.cumsum(Banking_data[:, 1])
print(cumsum_account_balance)

[ 29.99  79.98  99.97 189.96 205.95 275.94 315.93 395.92 421.91 481.9 ]


In [18]:
cumprod_transactioncount = np.cumprod(Banking_data[:, 3])
print(cumprod_transactioncount)

[4.20000000e+00 1.89000000e+01 7.18200000e+01 3.37554000e+02
 1.35021600e+03 5.80592880e+03 2.26431223e+04 1.04158363e+05
 4.27049287e+05 1.87901686e+06]


In [19]:
diff_concecutive_accountbalance = np.diff(Banking_data[:, 1])
print(diff_concecutive_accountbalance)

[ 20. -30.  70. -74.  54. -30.  40. -54.  34.]


In [20]:
gradient_account_balance = np.gradient(Banking_data[:, 1])
print(gradient_account_balance)

[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]


In [21]:
hist_account_balance, bin_edges = np.histogram(Banking_data[:, 1], bins=5)
print(f"Histogram counts: {hist_account_balance}")
print(f"Bin edges: {bin_edges}")

Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]
