In [1]:
import numpy as np

In [2]:
banking_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [3]:
random_ints=np.random.randint(1,1000,6)
print(random_ints)


[815 765 525 258 570 628]


In [4]:
random_floats = np.random.random(6)
print(random_floats)

[0.37016965 0.93425118 0.55286158 0.34393746 0.90773722 0.3671987 ]


In [5]:
normal_random = np.random.normal(700,100, 6)
print(normal_random)

[573.93759342 783.99703541 764.69580731 674.72845224 779.36545044
 654.67316989]


In [7]:
shuffled_data = banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1009.     25.99   67.      4.1    16.  ]]


In [8]:
np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [9]:
dot_product = np.dot(banking_data[:, 1], banking_data[:, 2])
print(f"Dot product: {dot_product:.2f}")

Dot product: 16527.35


In [10]:
cross_product = np.cross(banking_data[0, :3], banking_data[1, :3])
print(cross_product)

[-1289.87 13058.   19990.01]


In [11]:
price_norm = np.linalg.norm(banking_data[:, 1])
print(f"Price norm: {price_norm:.2f}")


Price norm: 171.24


In [12]:
matrix_3x3 = np.array([[2, 3,5], [1, 4,6],[7,8,9]])
determinant = np.linalg.det(matrix_3x3)
print(f"Matrix:\n{matrix_3x3}")
print(f"Determinant: {determinant}")

Matrix:
[[2 3 5]
 [1 4 6]
 [7 8 9]]
Determinant: -24.999999999999996


In [13]:
inverse_matrix = np.linalg.inv(matrix_3x3)
print(f"Inverse matrix:\n{inverse_matrix}")

Inverse matrix:
[[ 0.48 -0.52  0.08]
 [-1.32  0.68  0.28]
 [ 0.8  -0.2  -0.2 ]]


In [4]:
customers_ids_str = banking_data[:, 0].astype(str)
print(customers_ids_str)

['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [5]:
contains_100 = np.char.find(customers_ids_str, '100') >= 0
print(contains_100)

[ True  True  True  True  True  True  True  True  True False]


In [6]:
customers_ids_upper = np.char.upper(customers_ids_str)
print(customers_ids_upper)

['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [7]:
id_lengths = np.char.str_len(customers_ids_str)
print(id_lengths)

[6 6 6 6 6 6 6 6 6 6]


In [8]:
replaced_ids = np.char.replace(customers_ids_str, '100', 'CUST')
print(replaced_ids)

['CUST1.0' 'CUST2.0' 'CUST3.0' 'CUST4.0' 'CUST5.0' 'CUST6.0' 'CUST7.0'
 'CUST8.0' 'CUST9.0' '1010.0']


In [9]:
years_to_months = banking_data[:, 4] * 12
print(years_to_months)

[180.  96. 264.  60. 216. 144. 240.  84. 192. 120.]


In [10]:
avg_years = np.mean(banking_data[:, 4])
print(f"Average years in stock: {avg_years:.1f}")

Average years in stock: 13.3


In [5]:
active_customers = banking_data[banking_data[:, 4] > 5]
print(active_customers)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [6]:
total_years = np.sum(banking_data[:, 4])
print(f"Total years: {total_years} years")

Total years: 133.0 years


In [7]:
shortest_time_idx = np.argmin(banking_data[:, 4])
shortest_time_customers=banking_data[shortest_time_idx]
print(f"Customer ID: {shortest_time_customers[0]}, Years: {shortest_time_customers[4]}")

Customer ID: 1004.0, Years: 5.0


In [4]:
def calculate_interest(balance):
    interest_rate = 0.05
    return balance * interest_rate

balances = banking_data[:, 1]
interests = np.array([calculate_interest(balance)for balance in balances])
print(interests)

[1.4995 2.4995 0.9995 4.4995 0.7995 3.4995 1.9995 3.9995 1.2995 2.9995]


In [5]:
balance_range = np.where((banking_data[:, 1]) >30,'high','low')
print(balance_range)

['low' 'high' 'low' 'high' 'low' 'high' 'high' 'high' 'low' 'high']


In [6]:
conditions = [
    banking_data[:, 1] < 20,
    (banking_data[:, 1] >= 20) & (banking_data[:, 1] < 50),
    banking_data[:, 1] >= 50
]
choices = ['low', 'Medium', 'high']
credit_scores = np.select(conditions, choices, default='Unknown')
print(credit_scores)

['Medium' 'Medium' 'low' 'high' 'low' 'high' 'Medium' 'high' 'Medium'
 'high']


In [7]:
def low_interest(x): return x * 0.9  # 10% discount
def mid_interest(x): return x * 1.0  # No change
def high_interest(x): return x * 1.1  # 10% markup

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20, (banking_data[:, 1] >= 20) & (banking_data[:, 1] < 50), banking_data[:, 1] >= 50],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)

[29.99  49.99  17.991 98.989 14.391 76.989 39.99  87.989 25.99  65.989]


In [8]:
row_sums = np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[1095.19 1096.49 1126.79 1115.69 1137.99 1120.29 1126.89 1117.59 1122.09
 1118.39]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontally stacked: {hstacked}")

Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontally stacked: [1 2 3 4 5 6]


In [10]:
vstacked = np.vstack([arr1, arr2])
print(f"Vertically stacked:\n{vstacked}")

Vertically stacked:
[[1 2 3]
 [4 5 6]]


In [11]:
concatenated = np.concatenate([arr1, arr2], axis=0)
print(f"Concatenated along axis 0: {concatenated}")

Concatenated along axis 0: [1 2 3 4 5 6]


In [12]:
dstacked = np.dstack([arr1, arr2])
print(f"Depth-wise stacked:\n{dstacked}")

Depth-wise stacked:
[[[1 4]
  [2 5]
  [3 6]]]


In [13]:
col_stacked = np.column_stack([arr1, arr2])
print(f"Column stacked:\n{col_stacked}")

Column stacked:
[[1 4]
 [2 5]
 [3 6]]


In [15]:
arr_to_split = np.array([1,2,3,4,5,6,7,8,9])
split_parts = np.split(arr_to_split, 3)
print(f"original array:{arr_to_split}")
for i,part in enumerate(split_parts):
    print(f"part {i+1}: {part}")

original array:[1 2 3 4 5 6 7 8 9]
part 1: [1 2 3]
part 2: [4 5 6]
part 3: [7 8 9]


In [17]:
split_at_indices = np.split(arr_to_split,[3,6])
print(f"split at indices[3,6]:")
for i, part in enumerate(split_at_indices):
    print(f"part{i+1}: {part}")

split at indices[3,6]:
part1: [1 2 3]
part2: [4 5 6]
part3: [7 8 9]


In [18]:
arr_2d = np.array([[1,2,3],[4,5,6]])
hsplit_parts = np.hsplit(arr_2d,3)
print(f"original 2D array:\n{arr_2d}")
for i,part in enumerate(hsplit_parts):
    print(f"part {i+1}:\n{part}")


original 2D array:
[[1 2 3]
 [4 5 6]]
part 1:
[[1]
 [4]]
part 2:
[[2]
 [5]]
part 3:
[[3]
 [6]]


In [19]:
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:")
for i, part in enumerate(vsplit_parts):
    print(f"Part {i+1}:\n{part}")

Vertical parts:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]


In [20]:
chunks = np.array_split(arr_to_split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")

Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


In [21]:
repeat_elements = np.repeat(arr1, 3)
print(f"Original: {arr1}")
print(f"Repeated 3 times: {repeat_elements}")

Original: [1 2 3]
Repeated 3 times: [1 1 1 2 2 2 3 3 3]


In [22]:
tiled_array = np.tile(arr1, 2)
print(f"Original: {arr1}")
print(f"Tiled 2 times: {tiled_array}")

Original: [1 2 3]
Tiled 2 times: [1 2 3 1 2 3]


In [23]:
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(f"Original:\n{arr_2d_small}")
print(f"Tiled (2, 3):\n{tiled_2d}")

Original:
[[1 2]
 [3 4]]
Tiled (2, 3):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [24]:
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(f"Pattern: {pattern}")
print(f"Tiled 5 times: {pattern_tiled}")

Pattern: [1 0]
Tiled 5 times: [1 0 1 0 1 0 1 0 1 0]


In [25]:
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(arr1, repeat_counts)
print(f"Original: {arr1}")
print(f"Repeat counts: {repeat_counts}")
print(f"Result: {repeated_variable}")

Original: [1 2 3]
Repeat counts: [2, 1, 3]
Result: [1 1 2 3 3 3]


In [26]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([1, 2, 3])
arr_c = np.array([1, 2, 4])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Array C: {arr_c}")
print(f"A equals B: {np.array_equal(arr_a, arr_b)}")
print(f"A equals C: {np.array_equal(arr_a, arr_c)}")

Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False


In [27]:
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Array D: {arr_d}")
print(f"Array E: {arr_e}")
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")

Array D: [1. 2. 3.]
Array E: [1.001 2.001 3.001]
Arrays are close: True


In [28]:
logical_and = np.logical_and(arr_a > 1, arr_a < 3)
print(f"Array: {arr_a}")
print(f"Logical AND (1 < x < 3): {logical_and}")

Array: [1 2 3]
Logical AND (1 < x < 3): [False  True False]


In [29]:
logical_or = np.logical_or(arr_a == 1, arr_a == 3)
print(f"Array: {arr_a}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")

Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [30]:
logical_not = np.logical_not(arr_a == 2)
print(f"Array: {arr_a}")
print(f"Logical NOT (x != 2): {logical_not}")

Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


In [31]:
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
print(f"Original array: {arr_with_duplicates}")
print(f"Unique elements: {unique_elements}")

Original array: [1 2 2 3 3 3 4]
Unique elements: [1 2 3 4]


In [32]:
arr_f = np.array([1, 2, 3, 4])
arr_g = np.array([3, 4, 5, 6])
intersection = np.intersect1d(arr_f, arr_g)
print(f"Array F: {arr_f}")
print(f"Array G: {arr_g}")
print(f"Intersection: {intersection}")

Array F: [1 2 3 4]
Array G: [3 4 5 6]
Intersection: [3 4]


In [33]:
union = np.union1d(arr_f, arr_g)
print(f"Union: {union}")

Union: [1 2 3 4 5 6]


In [34]:
set_difference = np.setdiff1d(arr_f, arr_g)
print(f"Elements in F but not in G: {set_difference}")

Elements in F but not in G: [1 2]


In [35]:
symmetric_diff = np.setxor1d(arr_f, arr_g)
print(f"Symmetric difference: {symmetric_diff}")

Symmetric difference: [1 2 5 6]
