In [2]:
import numpy as np

In [3]:
data=np.random.randint(0,10,(3,3))

In [4]:
data

array([[0, 5, 8],
       [3, 2, 6],
       [2, 9, 7]])

In [ ]:
data.sum(axis=0),data.sum(axis=1),data.sum()
data.min(axis=0),data.min(axis=1),data.min()
data.max(axis=0),data.max(axis=1),data.max()
data.argmin(axis=0),data.argmin(axis=1),data.argmin()
data.argmax(axis=0),data.argmax(axis=1),data.argmax()
data.mean(axis=0),data.mean(axis=1),data.mean()

In [7]:
data.sum(axis=0)

array([ 5, 16, 21])

In [8]:
data.sum(axis=1)

array([13, 11, 18])

In [9]:
data.min(axis=0)

array([0, 2, 6])

In [12]:
data.min(axis=1)

array([0, 2, 2])

In [11]:
data.min()

np.int64(0)

In [13]:
data.max(axis=0)

array([3, 9, 8])

In [14]:
data.max(axis=1)

array([8, 6, 9])

In [15]:
data.max()

np.int64(9)

In [16]:
data.argmin(axis=0)

array([0, 1, 1])

In [17]:
data.argmin(axis=1)

array([0, 1, 0])

In [18]:
data.argmin()

np.int64(0)

In [19]:
data.argmax(axis=0)

array([1, 2, 0])

In [20]:
data.argmax(axis=1)

array([2, 2, 1])

In [21]:
data.argmax()

np.int64(7)

In [22]:
data.mean(axis=0)

array([1.66666667, 5.33333333, 7.        ])

In [23]:
data.mean(axis=1)

array([4.33333333, 3.66666667, 6.        ])

In [24]:
data.mean()

np.float64(4.666666666666667)